spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client                           #在Eureka官网上有这个服务的名字出现
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111
    initialization-mode: always
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.abc.entity                      #所有Entity所在的包

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka            #将提供者的服务注册到Eureka服务中心
  instance:
    instance-id: dept-8001.com                 #自定义服务名称信息
    prefer-ip-address: true                                 #注册的时候使用ip进行注册

#   监控信息的配置
info:
  app.name: zyh-microservicecloud-springcloudconfig01
  company.name: www.zyh.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client                           #在Eureka官网上有这个服务的名字出现
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111
    initialization-mode: always
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.xml
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.abc.entity                      #所有Entity所在的包

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka            #将提供者的服务注册到Eureka服务中心
  instance:
    instance-id: dept-8001.com                 #自定义服务名称信息
    prefer-ip-address: true                                 #注册的时候使用ip进行注册

#   监控信息的配置
info:
  app.name: zyh-microservicecloud-springcloudconfig01
  company.name: www.zyh.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}